controller_list:
  - name: fake_left_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_left_2f85_controller
    joints:
      []
initial:  # Define initial robot poses.
  - group: left_arm
    pose: left_home